# Generated by Django 4.0.2 on 2022-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(max_length=255),
        ),
    ]
