# Generated by Django 4.1 on 2023-11-09 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="seat_in_rows",
            new_name="seats_in_row",
        ),
    ]
