# Generated by Django 4.1 on 2023-03-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_cinemahall_genre_alter_movie_options_actor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={},
        ),
        migrations.AlterModelManagers(
            name="actor",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="actor",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="password",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="username",
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="cinema.actor"),
        ),
    ]
