# Generated by Django 4.1 on 2023-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
