# Generated by Django 4.1 on 2024-01-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_author_movie_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
