# Generated by Django 4.1 on 2023-08-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actors_cinemahall_genre_movie_actors_movie_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
    ]
