# Generated by Django 4.1 on 2023-11-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_movie_actors_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
