# Generated by Django 4.2.8 on 2023-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_moviesession_movie_actors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="full_name",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
