# Generated by Django 4.1 on 2023-03-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahalla_genre_movie_actors_movie_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinemaHalla',
            new_name='CinemaHall',
        ),
    ]
