# Generated by Django 4.0.2 on 2022-05-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='lost_name',
            new_name='last_name',
        ),
    ]
