# Generated by Django 4.1 on 2023-06-16 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_actor_cinemahal_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CinemaHal",
            new_name="CinemaHall",
        ),
    ]
