# Generated by Django 4.0.2 on 2022-10-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='sets_in_row',
            new_name='seats_in_row',
        ),
    ]
