# Generated by Django 4.1 on 2024-03-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="name",
            new_name="title",
        ),
    ]
