# Generated by Django 4.1 on 2024-03-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinema_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cinema",
            new_name="CinemaHall",
        ),
    ]
