# Generated by Django 4.1 on 2023-12-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_movie_actors_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='cinema.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='cinema.genre'),
        ),
    ]
