# Generated by Django 4.1 on 2023-11-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinnemahall_genre_movie_actors_movie_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinnemaHall',
            new_name='CinemaHall',
        ),
    ]
