# Generated by Django 4.1 on 2022-10-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_alter_movie_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cinemahall",
            options={"verbose_name": "cinema_hall"},
        ),
    ]
