# Generated by Django 4.1 on 2022-11-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
