# Generated by Django 4.0.4 on 2022-05-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="row",
            new_name="rows",
        ),
    ]
