# Generated by Django 4.0.4 on 2022-11-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actor_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="actor",
            new_name="actors",
        ),
    ]
