# Generated by Django 4.1 on 2024-02-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_remove_movie_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
