# Generated by Django 4.1 on 2024-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="rows",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
    ]
