# Generated by Django 4.1 on 2023-04-05 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_author_cinemahall_genre_alter_movie_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="Actor",
        ),
    ]
