# Generated by Django 4.1 on 2023-04-04 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="rows",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(999)]
            ),
        ),
    ]
