# Generated by Django 4.1 on 2022-11-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="row",
            new_name="rows",
        ),
    ]
