# Generated by Django 4.1 on 2024-01-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_cinemahall_seats_in_row"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinemahall",
            name="season_number",
        ),
    ]
