# Generated by Django 4.1 on 2024-01-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats_in_row',
            new_name='seats_in_rows',
        ),
    ]
