# Generated by Django 4.1 on 2023-09-16 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_rename_genre_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="actor",
            new_name="actors",
        ),
    ]
