# Generated by Django 4.1 on 2023-04-06 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_alter_cinemahall_rows_alter_cinemahall_seats_in_row_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="rows",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
