# Generated by Django 4.1 on 2022-11-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_remove_movie_genre_movie_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="genre",
            new_name="genres",
        ),
    ]
