# Generated by Django 4.0.2 on 2022-05-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_lost_name_actor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='row',
            new_name='rows',
        ),
    ]
