# Generated by Django 4.1 on 2024-03-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_rename_name_genre_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="title",
            new_name="name",
        ),
    ]
