# Generated by Django 4.0.4 on 2022-05-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_rename_row_cinemahall_rows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"verbose_name_plural": "Actors"},
        ),
        migrations.AlterModelOptions(
            name="cinemahall",
            options={"verbose_name_plural": "Cinema_Halls"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name_plural": "Movies"},
        ),
    ]
