# Generated by Django 4.1 on 2023-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cinema",
            "0003_remove_movie_actors_remove_movie_genres_movie_actors_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                null=True, related_name="actor_movies", to="cinema.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                null=True, related_name="genre_movies", to="cinema.genre"
            ),
        ),
    ]
