# Generated by Django 4.1 on 2024-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_rename_seats_in_a_row_cinemahall_seats_in_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(max_length=64),
        ),
    ]
