# Generated by Django 4.2.8 on 2023-12-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_remove_actor_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="full_name",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
