# Generated by Django 4.1 on 2024-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_remove_cinemahall_season_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="author",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.AddField(
            model_name="movie",
            name="author",
            field=models.ManyToManyField(to="cinema.actor"),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="cinema.genre"),
        ),
    ]
