# Generated by Django 4.1 on 2023-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_rename_actor_movie_actors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="cinema.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="cinema.genre"),
        ),
    ]
