# Generated by Django 4.0.4 on 2022-05-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cinema",
            "0004_alter_actor_options_alter_cinemahall_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name_plural": "Genres"},
        ),
    ]
