# Generated by Django 4.1 on 2022-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_rename_row_cinemahall_rows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemahall",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
