# Generated by Django 4.1 on 2024-01-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_rename_seats_in_row_cinemahall_seats_in_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats_in_rows',
            new_name='seats_in_row',
        ),
    ]
