# Generated by Django 4.0.4 on 2022-05-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_genre_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name_plural": "Actors",
            },
        ),
        migrations.AlterModelOptions(
            name="cinemahall",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Cinema_Halls",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"], "verbose_name_plural": "Genres"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["title"], "verbose_name_plural": "Movies"},
        ),
    ]
