# Generated by Django 4.1 on 2024-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0005_alter_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=64),
        ),
    ]
