# Generated by Django 4.1 on 2024-01-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cinema",
            "0005_remove_movie_author_remove_movie_genres_movie_author_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="author",
            new_name="authors",
        ),
    ]
