# Generated by Django 4.1 on 2024-01-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_rename_author_movie_authors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="authors",
            new_name="actors",
        ),
    ]
